# title = "ARPIT" # don't set for hostname

cache_dir = "/var/cache/tuilog" # default

[ascii_art]
# under base/assets/background/nixos.txt or use absolute path and default is nil
background = "background/nixos.txt"
# Color of the background ascii art, White is default
background_art_color = "Blue"
# under base/assets/icons/error.txt or use absolute path and error.txt is default
error_icon = "icons/error.txt"
