# title = "ARPIT" # don't set for hostname

cache_dir = "/var/cache/tuilog" # default
# directory where all xsessions are found

[ascii_art]
# under base/assets/background/nixos.txt or use absolute path and default is nil
background = "background/nixos.txt"
# Color of the background ascii art, White is default
background_art_color = "White"
# under base/assets/icons/error.txt or use absolute path and error.txt is default
error_icon = "icons/error.txt"

[[sessions]]
# The display name of the session, shown to the user.
name = "shell"
# The command to execute to start this session.
exec = ""

[[sessions]]
# The display name of the session, shown to the user.
name = "startx"
# The command to execute to start this session.
exec = "startx"
