title = "ARPIT CHAKLADAR" # empty for hostname

base = "/etc/tuilog" # default

[ascii_art]
# under base/assets/background/nixos.txt or use absolute path and default is nil
background = "nixos.txt"

# under base/assets/icons/error.txt or use absolute path and error.txt is default
error_icon = "error.txt"
